// Code generated by MockGen. DO NOT EDIT.
// Source: loan.go
//
// Generated by this command:
//
//	mockgen -source=loan.go -destination=mock/loan_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "loan_system/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// AddInvestment mocks base method.
func (m *MockUsecase) AddInvestment(ctx context.Context, loanID int64, investment model.Investment) (*model.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInvestment", ctx, loanID, investment)
	ret0, _ := ret[0].(*model.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInvestment indicates an expected call of AddInvestment.
func (mr *MockUsecaseMockRecorder) AddInvestment(ctx, loanID, investment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInvestment", reflect.TypeOf((*MockUsecase)(nil).AddInvestment), ctx, loanID, investment)
}

// ApproveLoan mocks base method.
func (m *MockUsecase) ApproveLoan(ctx context.Context, loanID int64, approval model.Approval) (*model.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveLoan", ctx, loanID, approval)
	ret0, _ := ret[0].(*model.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveLoan indicates an expected call of ApproveLoan.
func (mr *MockUsecaseMockRecorder) ApproveLoan(ctx, loanID, approval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveLoan", reflect.TypeOf((*MockUsecase)(nil).ApproveLoan), ctx, loanID, approval)
}

// CreateLoan mocks base method.
func (m *MockUsecase) CreateLoan(ctx context.Context, loan *model.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLoan", ctx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLoan indicates an expected call of CreateLoan.
func (mr *MockUsecaseMockRecorder) CreateLoan(ctx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLoan", reflect.TypeOf((*MockUsecase)(nil).CreateLoan), ctx, loan)
}

// DisburseLoan mocks base method.
func (m *MockUsecase) DisburseLoan(ctx context.Context, loanID int64, disbursement model.Disbursement) (*model.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisburseLoan", ctx, loanID, disbursement)
	ret0, _ := ret[0].(*model.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisburseLoan indicates an expected call of DisburseLoan.
func (mr *MockUsecaseMockRecorder) DisburseLoan(ctx, loanID, disbursement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisburseLoan", reflect.TypeOf((*MockUsecase)(nil).DisburseLoan), ctx, loanID, disbursement)
}

// FindAll mocks base method.
func (m *MockUsecase) FindAll(ctx context.Context) ([]*model.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*model.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUsecaseMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUsecase)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockUsecase) FindByID(ctx context.Context, id int64) (*model.Loan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Loan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUsecaseMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUsecase)(nil).FindByID), ctx, id)
}
